name: attendance_app
description: "Offline Flutter Geofencing Attendance App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ===============================
  # LOCATION & PERMISSIONS
  # ===============================
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # ===============================
  # STATE MANAGEMENT
  # ===============================
  provider: ^6.0.5

  # ===============================
  # LOCAL DATABASE (OFFLINE)
  # ===============================
  sqflite: ^2.3.0
  path: ^1.9.0

  # ===============================
  # UI ICONS
  # ===============================
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
